# This sample YAML config file is catered towards running the H264 Encoder Node on a Raspberry Pi based system

# The name of the topic to which the H264 encoder node should subscribe to obtain the feed desired to be encoded
# The topic must be a sensor_msgs/Image message
subscription_topic: "/virtual_event/deepracer/kvs_stream"

# The name of the topic to which H264 encoder node should publish the encoded video stream
# The topic will be a kinesis_video_msgs/KinesisVideoFrame message
publication_topic: "/virtual_event/b9/kvs/video/encoded"

# The numerator when expressing the frame rate as a rational number
fps_numerator: 15

# The denominator when expressing the frame rate as a rational number (default: 1)
fps_denominator: 1

# The target bit rate in bits per second of the output video stream
bitrate: 2048000
